# Generated by Django 4.1.1 on 2022-10-07 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='teachers',
            table='teachers',
        ),
    ]
