# Generated by Django 4.1.1 on 2022-10-05 21:16

import datetime
import django.core.validators
from django.db import migrations, models
import groups.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=100, validators=[django.core.validators.MinLengthValidator(2, 'Group name must be greater than 1 character')], verbose_name='Group Name')),
                ('start_date', models.DateField(blank=True, default=datetime.date.today, null=True, validators=[groups.validators.validate_start_date])),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'groups',
            },
        ),
    ]
